name: Build SoloLock
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ldid
        run: brew install ldid
      - name: Setup Theos & SDKs
        run: |
          export THEOS=$HOME/theos
          rm -rf $THEOS
          git clone --recursive https://github.com/theos/theos.git $THEOS
          rm -rf $THEOS/sdks
          git clone --depth=1 https://github.com/theos/sdks.git $THEOS/sdks
          echo "THEOS=$THEOS" >> $GITHUB_ENV
      - name: Build Package
        run: |
          chmod 0755 layout/DEBIAN/postinst
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SoloLock
          path: packages/*.deb
